use crate::ir;
use crate::types::BcType;

#[derive(Clone)]
pub struct NativeExternShim {
    pub extern_name: String,
    pub real_symbol: String,
    pub shim_symbol: String,
    pub params: Vec<(String, BcType)>,
    pub return_type: BcType,
}

pub enum NativeExternAbi {
    Direct,
    Shim(NativeExternShim),
}

pub fn classify(
    program: &ir::Program,
    name: &str,
    params: &[(String, BcType)],
    return_type: &BcType,
) -> Result<NativeExternAbi, String> {
    let mut needs_shim = false;
    for (_, ty) in params {
        match native_extern_type_kind(ty, program) {
            NativeExternTypeKind::Str => needs_shim = true,
            NativeExternTypeKind::Unsupported(reason) => {
                return Err(format!(
                    "extern function '{name}' parameter of type '{ty}' is not supported by the native backend ({reason})"
                ));
            }
            NativeExternTypeKind::Simple => {}
        }
    }

    match native_extern_type_kind(return_type, program) {
        NativeExternTypeKind::Str => needs_shim = true,
        NativeExternTypeKind::Unsupported(reason) => {
            return Err(format!(
                "extern function '{name}' return type '{return_type}' is not supported by the native backend ({reason})"
            ));
        }
        NativeExternTypeKind::Simple => {}
    }

    if !needs_shim {
        return Ok(NativeExternAbi::Direct);
    }

    for (_, ty) in params {
        c_type_for_generated_shim(ty, program).map_err(|reason| {
            format!(
                "extern function '{name}' parameter of type '{ty}' cannot be used in a generated native str ABI shim ({reason})"
            )
        })?;
    }
    c_type_for_generated_shim(return_type, program).map_err(|reason| {
        format!(
            "extern function '{name}' return type '{return_type}' cannot be used in a generated native str ABI shim ({reason})"
        )
    })?;

    let real_symbol = crate::c_name::mangle_c_name(name);
    let signature_key = signature_key(&real_symbol, params, return_type);
    let hash = fnv1a64(signature_key.as_bytes());
    let shim_symbol = format!(
        "__oscan_native_extern_shim_{hash:016x}_{}",
        c_identifier_suffix(&real_symbol)
    );

    Ok(NativeExternAbi::Shim(NativeExternShim {
        extern_name: name.to_string(),
        real_symbol,
        shim_symbol,
        params: params.to_vec(),
        return_type: return_type.clone(),
    }))
}

pub fn generate_source(
    shims: &[NativeExternShim],
    program: &ir::Program,
) -> Result<String, String> {
    if shims.is_empty() {
        return Ok(String::new());
    }

    let mut ordered = shims.to_vec();
    ordered.sort_by(|a, b| {
        a.shim_symbol
            .cmp(&b.shim_symbol)
            .then_with(|| a.extern_name.cmp(&b.extern_name))
    });

    let mut out = String::new();
    out.push_str("/* Generated by Oscan native backend: user extern str ABI shims. */\n");
    out.push_str("#include \"osc_runtime.h\"\n\n");

    for shim in &ordered {
        out.push_str(&format!(
            "extern {} {}({});\n",
            c_type_for_generated_shim(&shim.return_type, program)?,
            shim.real_symbol,
            real_param_list(shim, program)?
        ));
    }
    out.push('\n');

    for shim in &ordered {
        emit_shim_definition(&mut out, shim, program)?;
        out.push('\n');
    }

    Ok(out)
}

enum NativeExternTypeKind {
    Simple,
    Str,
    Unsupported(&'static str),
}

fn native_extern_type_kind(ty: &BcType, program: &ir::Program) -> NativeExternTypeKind {
    match ty {
        BcType::Str => NativeExternTypeKind::Str,
        BcType::Struct(_) => NativeExternTypeKind::Unsupported(
            "structs still require an explicit C shim; native does not classify aggregate C ABI layouts directly",
        ),
        BcType::Result(_, _) => NativeExternTypeKind::Unsupported(
            "Result still requires an explicit C shim; native does not classify aggregate C ABI layouts directly",
        ),
        BcType::Enum(name) if enum_has_payload(name, program) => NativeExternTypeKind::Unsupported(
            "payload enums still require an explicit C shim; native does not classify aggregate C ABI layouts directly",
        ),
        _ => NativeExternTypeKind::Simple,
    }
}

fn enum_has_payload(name: &str, program: &ir::Program) -> bool {
    program
        .enums
        .get(name)
        .map(|info| info.variants.iter().any(|(_, fields)| !fields.is_empty()))
        .unwrap_or(false)
}

fn c_type_for_generated_shim(ty: &BcType, program: &ir::Program) -> Result<String, String> {
    Ok(match ty {
        BcType::I32 => "int32_t".to_string(),
        BcType::I64 => "int64_t".to_string(),
        BcType::F64 => "double".to_string(),
        BcType::Bool => "uint8_t".to_string(),
        BcType::Str => "osc_str".to_string(),
        BcType::Unit => "void".to_string(),
        BcType::Handle => "uintptr_t".to_string(),
        BcType::Map
        | BcType::MapStrI32
        | BcType::MapStrI64
        | BcType::MapStrF64
        | BcType::MapI32Str
        | BcType::MapI32I32 => "osc_map*".to_string(),
        BcType::Array(_) | BcType::FixedArray(_, _) => "osc_array*".to_string(),
        BcType::Enum(name) if !enum_has_payload(name, program) => "int32_t".to_string(),
        BcType::Struct(_) => {
            return Err("structs are aggregate C ABI values".to_string());
        }
        BcType::Enum(_) => {
            return Err("payload enums are aggregate C ABI values".to_string());
        }
        BcType::Result(_, _) => {
            return Err("Result is an aggregate C ABI value".to_string());
        }
        BcType::FnPtr(_, _) => {
            return Err(
                "function pointer typedefs are not emitted into generated shim translation units"
                    .to_string(),
            );
        }
    })
}

fn real_param_list(shim: &NativeExternShim, program: &ir::Program) -> Result<String, String> {
    if shim.params.is_empty() {
        return Ok("void".to_string());
    }
    shim.params
        .iter()
        .enumerate()
        .map(|(i, (_, ty))| Ok(format!("{} p{i}", c_type_for_generated_shim(ty, program)?)))
        .collect::<Result<Vec<_>, String>>()
        .map(|parts| parts.join(", "))
}

fn shim_param_list(shim: &NativeExternShim, program: &ir::Program) -> Result<String, String> {
    let mut parts = Vec::new();
    if shim.return_type == BcType::Str {
        parts.push("osc_str *out".to_string());
    }
    for (i, (_, ty)) in shim.params.iter().enumerate() {
        let part = if *ty == BcType::Str {
            format!("const osc_str *p{i}")
        } else {
            format!("{} p{i}", c_type_for_generated_shim(ty, program)?)
        };
        parts.push(part);
    }
    if parts.is_empty() {
        Ok("void".to_string())
    } else {
        Ok(parts.join(", "))
    }
}

fn emit_shim_definition(
    out: &mut String,
    shim: &NativeExternShim,
    program: &ir::Program,
) -> Result<(), String> {
    let ret_c = if shim.return_type == BcType::Str {
        "void".to_string()
    } else {
        c_type_for_generated_shim(&shim.return_type, program)?
    };
    out.push_str(&format!(
        "{ret_c} {}({}) {{\n",
        shim.shim_symbol,
        shim_param_list(shim, program)?
    ));
    let args = shim
        .params
        .iter()
        .enumerate()
        .map(|(i, (_, ty))| {
            if *ty == BcType::Str {
                format!("*p{i}")
            } else {
                format!("p{i}")
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    match &shim.return_type {
        BcType::Unit => out.push_str(&format!("    {}({args});\n", shim.real_symbol)),
        BcType::Str => out.push_str(&format!("    *out = {}({args});\n", shim.real_symbol)),
        _ => out.push_str(&format!("    return {}({args});\n", shim.real_symbol)),
    }
    out.push_str("}\n");
    Ok(())
}

fn signature_key(real_symbol: &str, params: &[(String, BcType)], return_type: &BcType) -> String {
    let mut key = String::new();
    key.push_str(real_symbol);
    key.push('(');
    for (i, (_, ty)) in params.iter().enumerate() {
        if i > 0 {
            key.push(',');
        }
        key.push_str(&type_tag(ty));
    }
    key.push_str(")->");
    key.push_str(&type_tag(return_type));
    key
}

fn type_tag(ty: &BcType) -> String {
    match ty {
        BcType::I32 => "i32".to_string(),
        BcType::I64 => "i64".to_string(),
        BcType::F64 => "f64".to_string(),
        BcType::Bool => "bool".to_string(),
        BcType::Str => "str".to_string(),
        BcType::Unit => "unit".to_string(),
        BcType::Handle => "handle".to_string(),
        BcType::Map => "map".to_string(),
        BcType::MapStrI32 => "map_str_i32".to_string(),
        BcType::MapStrI64 => "map_str_i64".to_string(),
        BcType::MapStrF64 => "map_str_f64".to_string(),
        BcType::MapI32Str => "map_i32_str".to_string(),
        BcType::MapI32I32 => "map_i32_i32".to_string(),
        BcType::Struct(name) | BcType::Enum(name) => name.to_ascii_lowercase(),
        BcType::Array(elem) => format!("arr_{}", type_tag(elem)),
        BcType::FixedArray(elem, n) => format!("arr_{}_{}", type_tag(elem), n),
        BcType::Result(ok, err) => format!("result_{}_{}", type_tag(ok), type_tag(err)),
        BcType::FnPtr(params, ret) => {
            let params = params.iter().map(type_tag).collect::<Vec<_>>().join("_");
            format!("fnptr_{}_{}", params, type_tag(ret))
        }
    }
}

fn c_identifier_suffix(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.as_bytes()[0].is_ascii_digit() {
        out.insert(0, '_');
    }
    out
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}
