#!/usr/bin/env python3
"""Generate a categorized builtin-function table for README.md.

Reads @builtin structured comments from src/semantic.rs, groups them by
category, and either prints the markdown table to stdout or injects it
into README.md between marker comments.

Usage:
    python scripts/gen-builtin-table.py           # print to stdout
    python scripts/gen-builtin-table.py --inject   # update README.md in place
    python scripts/gen-builtin-table.py --check    # verify README.md is up to date
"""

import argparse
import re
import sys
from pathlib import Path
from collections import OrderedDict

# Category display order
CATEGORY_ORDER = [
    "I/O",
    "String",
    "Conversion",
    "Character",
    "Math",
    "Bitwise",
    "File I/O",
    "Filesystem",
    "Path",
    "Socket",
    "HashMap",
    "Array",
    "Date/Time",
    "System",
    "Environment",
    "Terminal",
    "Process",
    "Graphics",
    "TrueType",
    "Image",
    "TLS",
]

BEGIN_MARKER = "<!-- BEGIN BUILTIN TABLE -->"
END_MARKER = "<!-- END BUILTIN TABLE -->"

BUILTIN_RE = re.compile(
    r'// @builtin'
    r'\s+category="(?P<cat>[^"]+)"'
    r'\s+name="(?P<name>[^"]+)"'
    r'\s+sig="(?P<sig>[^"]+)"'
    r'\s+desc="(?P<desc>[^"]+)"'
)


def find_repo_root() -> Path:
    """Walk up from this script to find the repo root (contains Cargo.toml)."""
    d = Path(__file__).resolve().parent
    while d != d.parent:
        if (d / "Cargo.toml").exists():
            return d
        d = d.parent
    # Fallback: assume script is in scripts/ under repo root
    return Path(__file__).resolve().parent.parent


def extract_builtins(semantic_path: Path) -> OrderedDict:
    """Parse @builtin comments and return {category: [(sig, desc), ...]}."""
    text = semantic_path.read_text(encoding="utf-8")
    groups: dict[str, list[tuple[str, str]]] = {}

    for m in BUILTIN_RE.finditer(text):
        cat = m.group("cat")
        sig = m.group("sig")
        desc = m.group("desc")
        groups.setdefault(cat, []).append((sig, desc))

    # Order by CATEGORY_ORDER, then any unknown categories alphabetically
    ordered = OrderedDict()
    for cat in CATEGORY_ORDER:
        if cat in groups:
            ordered[cat] = groups.pop(cat)
    for cat in sorted(groups.keys()):
        ordered[cat] = groups[cat]

    return ordered


def generate_table(groups: OrderedDict) -> str:
    """Build markdown table sections from grouped builtins."""
    total = sum(len(fns) for fns in groups.values())
    lines = [f"**{total} built-in functions** across {len(groups)} categories.\n"]

    for cat, fns in groups.items():
        lines.append(f"### {cat} ({len(fns)} functions)\n")
        lines.append("| Function | Description |")
        lines.append("|----------|-------------|")
        for sig, desc in fns:
            lines.append(f"| `{sig}` | {desc} |")
        lines.append("")  # blank line between categories

    return "\n".join(lines).rstrip() + "\n"


def generate_builtins_doc(groups: OrderedDict, table: str) -> str:
    """Full standalone docs/builtins.md content."""
    header = (
        "# Oscan Built-in Functions\n\n"
        "This file is auto-generated by `scripts/gen-builtin-table.py` from\n"
        "`@builtin` annotations in `src/semantic.rs`. Do not edit by hand — run\n"
        "`python scripts/gen-builtin-table.py --inject` to update it.\n\n"
    )
    return header + table


def generate_readme_summary(groups: OrderedDict) -> str:
    """Short summary block for README (replaces the full table)."""
    total = sum(len(fns) for fns in groups.values())
    cats = ", ".join(groups.keys())
    return (
        f"**{total} built-in functions** across {len(groups)} categories: "
        f"{cats}.\n\n"
        "See the [full built-in function reference](docs/builtins.md) for "
        "signatures and descriptions.\n"
    )


def inject_between_markers(path: Path, payload: str) -> str:
    """Replace content between markers in a file. Returns new content."""
    text = path.read_text(encoding="utf-8")
    begin_idx = text.find(BEGIN_MARKER)
    end_idx = text.find(END_MARKER)

    if begin_idx == -1 or end_idx == -1:
        print(f"ERROR: Markers not found in {path}", file=sys.stderr)
        print(f"  Expected: {BEGIN_MARKER}", file=sys.stderr)
        print(f"       and: {END_MARKER}", file=sys.stderr)
        sys.exit(1)

    before = text[: begin_idx + len(BEGIN_MARKER)]
    after = text[end_idx:]
    return before + "\n\n" + payload + "\n" + after


def main():
    parser = argparse.ArgumentParser(description="Generate builtin function table")
    parser.add_argument(
        "--inject", action="store_true", help="Update README.md in place"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify README.md is up to date (exit 1 if stale)",
    )
    args = parser.parse_args()

    root = find_repo_root()
    semantic_path = root / "src" / "semantic.rs"
    readme_path = root / "README.md"
    builtins_doc_path = root / "docs" / "builtins.md"

    if not semantic_path.exists():
        print(f"ERROR: {semantic_path} not found", file=sys.stderr)
        sys.exit(1)

    groups = extract_builtins(semantic_path)
    if not groups:
        print("ERROR: No @builtin annotations found in semantic.rs", file=sys.stderr)
        sys.exit(1)

    table = generate_table(groups)
    builtins_doc = generate_builtins_doc(groups, table)
    readme_summary = generate_readme_summary(groups)
    total = sum(len(fns) for fns in groups.values())

    if args.check:
        if not readme_path.exists():
            print(f"ERROR: {readme_path} not found", file=sys.stderr)
            sys.exit(1)
        expected_readme = inject_between_markers(readme_path, readme_summary)
        actual_readme = readme_path.read_text(encoding="utf-8")
        readme_ok = expected_readme == actual_readme
        doc_ok = (
            builtins_doc_path.exists()
            and builtins_doc_path.read_text(encoding="utf-8") == builtins_doc
        )
        if readme_ok and doc_ok:
            print(f"OK: README.md and docs/builtins.md are up to date ({total} functions)")
            sys.exit(0)
        else:
            if not readme_ok:
                print("ERROR: README.md builtin summary is out of date.", file=sys.stderr)
            if not doc_ok:
                print("ERROR: docs/builtins.md is out of date.", file=sys.stderr)
            print("Run: python scripts/gen-builtin-table.py --inject", file=sys.stderr)
            sys.exit(1)

    if args.inject:
        if not readme_path.exists():
            print(f"ERROR: {readme_path} not found", file=sys.stderr)
            sys.exit(1)
        new_readme = inject_between_markers(readme_path, readme_summary)
        readme_path.write_text(new_readme, encoding="utf-8")
        builtins_doc_path.parent.mkdir(parents=True, exist_ok=True)
        builtins_doc_path.write_text(builtins_doc, encoding="utf-8")
        print(f"Injected {total} builtins summary into {readme_path}")
        print(f"Wrote full table to {builtins_doc_path}")
    else:
        print(table)


if __name__ == "__main__":
    main()
